import {useEffect,useState} from 'react';
import {createPortal} from 'react-dom';
import {Bell,MessageSquare,X,Send} from 'lucide-react';
import {chatCall,supabase} from '../lib/supabase';
export async function registerInterest(item:any,channel:string){
 const {data}=await supabase.auth.getSession();
 if(!data.session){sessionStorage.setItem('vm-return',location.pathname);location.assign('/login');throw Error('Please sign in with Google first.');}
 return chatCall('interest',{listingId:item.id,channel});
}
export function openConversation(threadId:string){window.dispatchEvent(new CustomEvent('vm-open-chat',{detail:threadId}));}
export default function Inbox({user}:{user:any}){
 const [open,setOpen]=useState(false),[threads,setThreads]=useState<any[]>([]),[selected,setSelected]=useState(''),[messages,setMessages]=useState<any[]>([]),[body,setBody]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[more,setMore]=useState(false);
 const unread=threads.reduce((n,t)=>n+Number(t.unread),0),thread=threads.find(t=>t.id===selected);
 async function refresh(){try{const r=await chatCall('inbox');setThreads(r.threads);setError('')}catch(e:any){setError(e.message)}}
 useEffect(()=>{if(!user)return;refresh();const timer=setInterval(()=>{if(!document.hidden)refresh()},10000);const fn=(e:any)=>{setSelected(e.detail);setOpen(true);refresh()};window.addEventListener('vm-open-chat',fn);return()=>{clearInterval(timer);window.removeEventListener('vm-open-chat',fn)}},[user?.id]);
 useEffect(()=>{if(!open||!selected)return;let active=true;setMessages([]);setBody('');setLoading(true);
 async function read(){try{const r=await chatCall('messages',{threadId:selected});if(!active)return;setMessages(old=>{const ids=new Set(r.messages.map((m:any)=>m.id));return [...old.filter(m=>!ids.has(m.id)),...r.messages].sort((a,b)=>a.id-b.id)});setMore(r.messages.length===100);setLoading(false);if(r.messages.length)await chatCall('seen',{threadId:selected,lastId:r.messages.at(-1).id});if(active)refresh()}catch(e:any){if(active){setError(e.message);setLoading(false)}}}
 read();const timer=setInterval(()=>{if(!document.hidden)read()},5000);return()=>{active=false;clearInterval(timer)}},[open,selected]);
 async function older(){try{const r=await chatCall('messages',{threadId:selected,before:messages[0]?.id});setMessages(old=>[...r.messages,...old]);setMore(r.messages.length===100)}catch(e:any){setError(e.message)}}
 async function send(e:any){e.preventDefault();if(busy||!body.trim())return;setBusy(true);try{await chatCall('send',{threadId:selected,body});setBody('');const r=await chatCall('messages',{threadId:selected});setMessages(r.messages);if(r.messages.length)await chatCall('seen',{threadId:selected,lastId:r.messages.at(-1).id});await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <><button className="channel inbox-trigger" onClick={()=>{if(!user){location.assign('/login');return}setOpen(true);refresh()}} aria-label={`Notifications and messages, ${unread} unread`}><Bell size={18}/><span>Inbox</span>{unread>0&&<b>{unread}</b>}</button>{open&&createPortal(<div className="chat-backdrop" onClick={()=>setOpen(false)}><section className="chat-panel" role="dialog" aria-modal="true" aria-label="Private inbox" onClick={e=>e.stopPropagation()}><div className="chat-heading"><h2><MessageSquare size={21}/>Interested buyers & chats</h2><button className="quiet" aria-label="Close inbox" onClick={()=>setOpen(false)}><X/></button></div>{error&&<div className="notice" role="alert">{error}<button onClick={refresh}>Retry</button></div>}<div className="chat-layout"><aside><p className="form-help">New interest and replies appear here. Unread conversations are your notifications.</p>{!threads.length&&<p>No conversations yet.</p>}{threads.map(t=><button key={t.id} disabled={busy} className={'thread '+(selected===t.id?'active':'')} onClick={()=>setSelected(t.id)}><strong>{t.peerName}{Number(t.unread)>0&&<b>{t.unread}</b>}</strong><span>{t.title}</span><small>{t.buyer===user.id?'Your interest':'Interested buyer'} · {t.channel}{t.sold?' · Sold':''}</small><p>{t.lastMessage}</p></button>)}</aside><div className="chat-content">{thread?<><div className="chat-context"><a href={'/account/'+thread.listing}>{thread.title}</a><p>{thread.peerName} · {thread.channel}</p>{thread.seller===user.id&&<details><summary>Record this sale</summary><p>Buyer member ID: <code>{thread.buyer}</code></p><a href="/profile">Open Trust & activity to record and confirm the sale.</a></details>}</div><div className="chat-messages" aria-live="polite">{loading&&<p>Loading conversation…</p>}{more&&<button className="quiet" onClick={older}>Load older messages</button>}{messages.map(m=><article className={'chat-bubble '+(m.sender===user.id?'mine':'')} key={m.id}><p>{m.body}</p><small>{m.sender===user.id?'You':thread.peerName} · {new Date(m.created).toLocaleString()}</small></article>)}</div><form className="chat-compose" onSubmit={send}><textarea aria-label="Your message" maxLength={3000} value={body} onChange={e=>setBody(e.target.value)} placeholder="Discuss availability and transaction details…" required/><button className="primary" disabled={busy||!body.trim()}><Send size={17}/>{busy?'Sending…':'Send'}</button></form><p className="form-help">Mine/Buy expresses interest. Agree on the transaction here or through your chosen contact channel.</p></>:<div className="empty">Select a conversation to reply.</div>}</div></div></section></div>,document.body)}</>;
}
