'use client';
import {useState} from 'react';
import {Search,Check,X} from 'lucide-react';
import catalog from '../lib/catalog.json';
export const categories=[{key:'weapons',label:'Weapon skins'},{key:'cards',label:'Player cards'},{key:'buddies',label:'Gun buddies'},{key:'sprays',label:'Sprays'}];
export type Inventory=Record<string,string[]>;
export const blankInventory=():Inventory=>({weapons:[],cards:[],buddies:[],sprays:[]});
export function itemsFor(inv:Inventory,key:string){return (catalog as any)[key].filter((x:any)=>(inv?.[key]||[]).includes(x.id))}
export function InventoryPicker({value,onChange}:{value:Inventory,onChange:(v:Inventory)=>void}){
 const [tab,setTab]=useState('weapons'),[query,setQuery]=useState(''),[weapon,setWeapon]=useState('All weapons'),[onlySelected,setOnlySelected]=useState(false),[limit,setLimit]=useState(48);
 const items=(catalog as any)[tab].filter((x:any)=>x.name.toLowerCase().includes(query.toLowerCase())&&(tab!=='weapons'||weapon==='All weapons'||x.weapon===weapon)&&(!onlySelected||value[tab].includes(x.id)));
 const total=categories.reduce((n,c)=>n+value[c.key].length,0);
 function toggle(id:string){onChange({...value,[tab]:value[tab].includes(id)?value[tab].filter(x=>x!==id):[...value[tab],id]})}
 return <fieldset className="inventory-picker"><legend>Account collection <span>{total} selected</span></legend><p className="form-help">Select only the items included in your account. Counts update automatically.</p><div className="inventory-tabs">{categories.map(c=><button type="button" key={c.key} className={tab===c.key?'selected':''} onClick={()=>{setTab(c.key);setQuery('');setLimit(48)}}>{c.label}<span>{value[c.key].length}</span></button>)}</div><div className="picker-controls"><label className="search"><Search size={16}/><input value={query} onChange={e=>{setQuery(e.target.value);setLimit(48)}} placeholder={'Search '+categories.find(c=>c.key===tab)?.label.toLowerCase()}/></label>{tab==='weapons'&&<select aria-label="Filter by weapon" value={weapon} onChange={e=>{setWeapon(e.target.value);setLimit(48)}}>{['All weapons',...new Set((catalog as any).weapons.map((x:any)=>x.weapon))].map((x:any)=><option key={x}>{x}</option>)}</select>}</div><div className="picker-meta"><button type="button" className={onlySelected?'selected':''} onClick={()=>setOnlySelected(!onlySelected)}>{onlySelected?'Show all items':'Show selected only'}</button><span>{items.length} items</span></div><div className={'inventory-grid picker-grid '+tab}>{items.slice(0,limit).map((x:any)=><button type="button" key={x.id} aria-pressed={value[tab].includes(x.id)} className={'inventory-item '+(value[tab].includes(x.id)?'chosen':'')} onClick={()=>toggle(x.id)}><img src={x.image} alt="" loading="lazy"/><span>{x.name}</span><i>{value[tab].includes(x.id)?<Check size={14}/>:<PlusMark/>}</i></button>)}</div>{!items.length&&<p className="empty-inline">No matching items. Try another search.</p>}{items.length>limit&&<button type="button" className="secondary full" onClick={()=>setLimit(limit+48)}>Load more items ({items.length-limit} remaining)</button>}<div className="selected-chips">{categories.map(c=><span key={c.key}>{value[c.key].length} {c.label.toLowerCase()}</span>)}</div></fieldset>
}
function PlusMark(){return <span>+</span>}
export function InventoryViewer({inventory,legacy=false}:{inventory:Inventory,legacy?:boolean}){
 const [tab,setTab]=useState('weapons'),[query,setQuery]=useState('');
 const items=itemsFor(inventory,tab).filter((x:any)=>x.name.toLowerCase().includes(query.toLowerCase()));
 return <section className="inventory-viewer"><div className="section-head"><h2>Full account collection</h2><span className="collection-source">Seller-declared inventory</span></div><div className="inventory-tabs">{categories.map(c=><button key={c.key} className={tab===c.key?'selected':''} onClick={()=>{setTab(c.key);setQuery('')}}>{c.label}<span>{inventory?.[c.key]?.length||0}</span></button>)}</div><label className="search wide"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search this account's collection…"/></label><div className={'inventory-grid '+tab}>{items.map((x:any)=><div className="inventory-item" key={x.id}><img src={x.image} loading="lazy" alt={x.name}/><span>{x.name}</span></div>)}</div>{!items.length&&<div className="empty"><h3>{query?'No matching items':legacy?'Inventory not provided':'No items listed in this category'}</h3><p>{legacy?'This older listing does not contain an itemized inventory. Ask the seller for collection details.':query?'Try a different search.':'The seller has not selected any items here.'}</p></div>}</section>
}
