import {appFetch} from '../lib/supabase';
'use client';
import {useState,useEffect} from 'react';
import {Search,Plus,SlidersHorizontal,Shield,MessageSquare,User,Heart,X,Check,ChevronDown,Gamepad2,Layers,LogOut,Menu} from 'lucide-react';
import skins from '../lib/skins.json';
import catalog from '../lib/catalog.json';
import ContactButtons from './contact';
import TrustPanel,{TrustBadge,ProfileMetrics,ReportForm} from './trust-panel';
import {InventoryPicker,InventoryViewer,blankInventory,categories,itemsFor,type Inventory} from './inventory';
const money=(n:any)=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:0}).format(+n);
const ranks=['Iron','Bronze','Silver','Gold','Platinum','Diamond','Ascendant','Immortal','Radiant'];
const samples=[['Kuronami collector’s account',8900,'Ascendant',182,34,6,'Kairo'],['Reaver + Prime essentials',3500,'Diamond',126,18,0,'Mika'],['Oni collection • clean loadout',5200,'Platinum',154,24,3,'YoruMain'],['Premium Vandal collection',12500,'Immortal',241,56,2,'Astra'],['Your first premium account',1800,'Silver',68,8,1,'Kenji'],['RGX collection + knife',6800,'Diamond',167,29,5,'Sage']].map((a,i)=>({id:'demo-'+i,kind:'listing',title:a[0],price:a[1],rank:a[2],level:a[3],skins:a[4],image:skins[+a[5]].image,author:a[6],owner:'seller-'+i,region:'APAC',description:'Sample account showcasing a curated skin collection. This is a preview listing and is not available for purchase.',demo:true,contact:'',created:'2026-10-01'}));
const topics=[{id:'topic-1',title:'Show us your favorite Vandal collection',category:'Collections',message:'Reaver, Prime, or Kuronami? Which collection would you choose for your daily loadout?',author:'Kairo',demo:true},{id:'topic-2',title:'What screenshots should a listing include?',category:'Discussion',message:'A full collection view, rank, region, and account level help buyers compare listings. What else would you want to see?',author:'Mika',demo:true},{id:'topic-3',title:'Community reminder: keep account details private',category:'Community',message:'Never post passwords, recovery codes, or payment credentials in listings or public discussions.',author:'Community',demo:true}];
export default function Market({initial,accountId}:{initial:string,accountId?:string}){
const [trust,setTrust]=useState<any>(null),[trustError,setTrustError]=useState('');
const [inventory,setInventory]=useState<Inventory>(blankInventory());
const [view,setView]=useState(initial),[records,setRecords]=useState<any[]>([]),[user,setUser]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[rank,setRank]=useState('All ranks'),[budget,setBudget]=useState('Any price'),[sort,setSort]=useState('Featured'),[modal,setModal]=useState<any>(null),[selected,setSelected]=useState<any>(null),[favorites,setFavorites]=useState<string[]>([]),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false),[category,setCategory]=useState('All topics');
async function refreshTrust(){try{const r=await appFetch('/api/trust');const d:any=await r.json();if(!r.ok){if(r.status===401){setTrust(null);return}throw Error(d.error)}setTrust(d);setTrustError('')}catch(e:any){setTrustError(e.message)}}
async function refresh(){try{const r=await appFetch('/api/market');const d:any=await r.json();if(!r.ok)throw Error(d.error);setRecords(d.records);setUser(d.user);setError('');await refreshTrust();}catch(e:any){setError(e.message)}finally{setLoading(false)}}
useEffect(()=>{refresh()},[]);
function navigate(v:string){setView(v);setSelected(null);setQuery('');window.history.pushState({},'',v==='market'?'/':'/'+v)}
useEffect(()=>{const fn=()=>{if(location.pathname.startsWith('/account/')){location.reload();return}setView(location.pathname.slice(1)||'market')};window.addEventListener('popstate',fn);return()=>window.removeEventListener('popstate',fn)},[]);
async function save(kind:string,data:any){setSaving(true);setNotice('');try{const r=await appFetch('/api/market',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,data})});const d:any=await r.json();if(!r.ok)throw Error(d.error);setModal(null);setNotice('Saved successfully.');await refresh()}catch(e:any){setNotice(e.message)}finally{setSaving(false)}}
function open(kind:string,extra:any={}){setNotice('');if(kind==='listing')setInventory(blankInventory());setModal({kind,...extra})}
const demoAccounts=samples.map((x,i)=>{const inv=blankInventory();inv.weapons=(catalog.weapons.filter(s=>s.name.toLowerCase().includes(String(x.title).split(' ')[0].toLowerCase())).slice(0,5).map(s=>s.id));inv.cards=catalog.cards.slice(i*2,i*2+3).map(s=>s.id);inv.buddies=catalog.buddies.slice(i*2,i*2+2).map(s=>s.id);inv.sprays=catalog.sprays.slice(i*3,i*3+4).map(s=>s.id);return {...x,inventory:inv,skins:inv.weapons.length,urgency:i%3===0?'rush':'normal',sold:false}});
const all=[...records.filter(x=>x.kind==='listing'),...demoAccounts];
const account=all.find(x=>x.id===accountId);
function fullAccount(x:any){window.location.assign('/account/'+encodeURIComponent(x.id))}
let list=all.filter(x=>(x.title+' '+x.description+' '+x.author).toLowerCase().includes(query.toLowerCase())&&(rank==='All ranks'||x.rank===rank)&&(budget==='Any price'||+x.price<=+budget));
if(sort==='Price: low to high')list.sort((a,b)=>+a.price-+b.price);if(sort==='Price: high to low')list.sort((a,b)=>+b.price-+a.price);if(view==='saved')list=list.filter(x=>favorites.includes(x.id));
const profile=selected||{owner:user?.id,name:records.find(x=>x.kind==='profile'&&x.owner===user?.id)?.name||user?.name||'Your seller profile'};
const profileRecord=records.find(x=>x.kind==='profile'&&x.owner===profile.owner);
const profileMember=trust?.members?.find((m:any)=>m.id===profile.owner);
const sellerProfile=(id:string)=>records.find(x=>x.kind==='profile'&&x.owner===id);
const sellerMember=(id:string)=>trust?.members?.find((m:any)=>m.id===id);
const urgencyBadge=(x:any)=><span className={'urgency '+(x.sold?'sold':x.urgency==='rush'?'rush':'normal')}>{x.sold?'Sold':x.urgency==='rush'?'Rush sale':'Not rush'}</span>;
function toggle(id:string){setFavorites(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id])}
function card(x:any){return <article className="listing" key={x.id}><button className="art" onClick={()=>open('detail',{item:x})}><span className={'rank rank-'+x.rank}>{x.rank}</span><img src={x.image||skins[0].image} alt={x.title+' skin preview'}/><span className="count"><Layers size={13}/>{x.skins} skins</span></button><button className={'save '+(favorites.includes(x.id)?'active':'')} aria-label="Save listing for this visit" onClick={()=>toggle(x.id)}><Heart size={18} fill={favorites.includes(x.id)?'currentColor':'none'}/></button><div className="listing-body"><div className="listing-badges">{urgencyBadge(x)}{!x.demo&&<TrustBadge member={sellerMember(x.owner)}/>}</div><div className="meta">{x.region} <span>•</span> Level {x.level} <span className="demo">{x.demo?'SAMPLE':'NEW'}</span></div><button className="listing-title" onClick={()=>open('detail',{item:x})}>{x.title}</button><div className="seller-line"><button onClick={()=>{setSelected({owner:x.owner,name:x.author});setView('profile')}}><span className="avatar small">{x.author?.[0]}</span>{x.author}</button><span>{x.demo?'Preview seller':'Seller'}</span></div><div className="price-line"><strong>{money(x.price)}</strong><button onClick={()=>open('detail',{item:x})}>View account</button></div></div></article>}
if(user?.suspended)return <main className="suspension-screen"><Shield size={48}/><span className="eyebrow">ACCOUNT SUSPENDED</span><h1>Your access is temporarily paused.</h1><p>Your credits reached zero after administrator-confirmed reports.</p><p>Access returns on <strong>{new Date(user.suspendedUntil).toLocaleString()}</strong> with 25 credits.</p><button className="primary" onClick={refresh}>Check access again</button><a className="quiet" href="/logout" target="_top">Sign out</a></main>;
return <div className="site"><header><a className="brand" href="/" onClick={e=>{e.preventDefault();navigate('market')}}><span className="brandmark">V</span><span>VALORANT<span className="brand-sub">BUY & SELL</span></span></a><nav><button className={view==='market'?'current':''} onClick={()=>navigate('market')}>Marketplace</button><button className={view==='collection'?'current':''} onClick={()=>navigate('collection')}>Skin collection</button><button className={view==='community'?'current':''} onClick={()=>navigate('community')}>Community</button></nav><div className="header-actions"><button className="icon" aria-label="Saved listings" onClick={()=>setView('saved')}><Heart size={20}/>{favorites.length>0&&<span>{favorites.length}</span>}</button><button className="icon" aria-label="My profile" onClick={()=>navigate('profile')}><User size={20}/></button><button className="primary" onClick={()=>open('listing')}><Plus size={17}/>Sell account</button></div></header><div className="mobile-nav"><button onClick={()=>navigate('market')}>Marketplace</button><button onClick={()=>navigate('collection')}>Collection</button><button onClick={()=>navigate('community')}>Community</button></div><main>
{view==='account'&&(loading?<div className="empty">Loading account…</div>:account?<><button className="quiet" onClick={()=>navigate('market')}>Back to marketplace</button><section className="account-overview"><div className="account-art"><img src={account.image||skins[0].image} alt={account.title}/></div><div><span className="eyebrow">{account.demo?'SAMPLE ACCOUNT':'ACCOUNT DETAILS'} · {account.region}</span><h1>{account.title}</h1><div className="listing-badges">{urgencyBadge(account)}{!account.demo&&<TrustBadge member={sellerMember(account.owner)}/>}</div><strong className="detail-price">{money(account.price)}</strong><div className="facts"><span>Rank<strong>{account.rank}</strong></span><span>Level<strong>{account.level}</strong></span><span>Region<strong>{account.region}</strong></span></div><p>{account.description}</p><button className="quiet" onClick={()=>{setSelected({owner:account.owner,name:account.author});setView('profile')}}><User size={17}/>View {account.author}'s profile</button>{account.demo?<div className="notice">Sample collection for preview only. This account is not for sale.</div>:<>{account.sold?<div className="notice">This account has a confirmed completed sale.</div>:<><ContactButtons profile={sellerProfile(account.owner)} item={account}/><button className="secondary full" onClick={()=>open('inquiry',{item:account})}>Send website inquiry</button></>}{user?.id!==account.owner&&<button className="quiet report-link" onClick={()=>open('report',{item:account})}>Report this listing</button>}</>}</div></section><div className="inventory-totals">{categories.map(c=><div key={c.key}><strong>{account.inventory?.[c.key]?.length||0}</strong><span>{c.label}</span></div>)}</div><InventoryViewer inventory={account.inventory||blankInventory()} legacy={!account.inventory}/></>:<div className="empty"><h2>{error?'Account could not be loaded':'Account not found'}</h2><p>{error||'This listing may no longer be available.'}</p>{error&&<button className="secondary" onClick={refresh}>Retry</button>}<button className="primary" onClick={()=>navigate('market')}>Browse accounts</button></div>)}
{notice&&!modal&&<div className="notice" role="status">{notice}</div>}
{view==='market'||view==='saved'?<><section className="intro"><div><div className="eyebrow"><span/>THE PH COMMUNITY MARKETPLACE</div><h1>Your next collection.<br/><em>Your next main.</em></h1><p>Explore accounts, compare loadouts, and connect with sellers.</p><div className="intro-actions"><button className="primary" onClick={()=>document.getElementById('browse')?.scrollIntoView({behavior:'smooth'})}>Explore accounts</button><button className="quiet" onClick={()=>navigate('community')}><MessageSquare size={17}/>Join the conversation</button></div></div><div className="hero-art"><span className="art-label">COLLECTION SPOTLIGHT / 01</span><img src={skins[6].image} alt="Kuronami Vandal"/><div className="hero-caption"><div><span>KURONAMI</span><small>Vandal collection</small></div><span className="outline-tag">EXCLUSIVE EDITION</span></div></div></section><div className="info-strip"><span><Gamepad2 size={18}/>APAC accounts</span><span><Layers size={18}/>Collections at a glance</span><span><MessageSquare size={18}/>Connect directly with sellers</span><span className="sample-note">Preview listings included</span></div><section id="browse"><div className="section-head"><div className="heading-line"><h2>{view==='saved'?'Saved for this visit':'Explore the marketplace'}</h2><span>{list.length} accounts</span></div><button className="quiet" onClick={()=>{setQuery('');setRank('All ranks');setBudget('Any price')}}>Reset filters</button></div><div className="filters"><label className="search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search skins, accounts, or sellers…"/></label><label><span className="sr-only">Rank</span><select value={rank} onChange={e=>setRank(e.target.value)}>{['All ranks',...ranks].map(x=><option key={x}>{x}</option>)}</select></label><label><span className="sr-only">Maximum price</span><select value={budget} onChange={e=>setBudget(e.target.value)}><option>Any price</option><option value="3000">Under ₱3,000</option><option value="6000">Under ₱6,000</option><option value="10000">Under ₱10,000</option></select></label><label><span className="sr-only">Sort</span><select value={sort} onChange={e=>setSort(e.target.value)}>{['Featured','Price: low to high','Price: high to low'].map(x=><option key={x}>{x}</option>)}</select></label></div>{error&&<div className="notice">{error} <button onClick={refresh}>Retry</button></div>}<div className="grid">{list.map(card)}</div>{!list.length&&<div className="empty"><Search/><h3>No accounts found</h3><p>Try another search or adjust your filters.</p></div>}</section></>:null}
{view==='collection'&&<><div className="page-heading"><span className="eyebrow">THE ARMORY</span><h1>Find your signature skin.</h1><p>Explore weapon skins, then find matching account listings.</p></div><label className="search wide"><Search size={20}/><input placeholder="Search the collection…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="skin-grid">{skins.filter(s=>s.name.toLowerCase().includes(query.toLowerCase())).map((s,i)=><button className="skin-tile" key={s.name} onClick={()=>{navigate('market');setQuery(s.name.split(' ')[0])}}><span className="eyebrow">{i===7?'MELEE':'WEAPON COLLECTION'}</span><img src={s.image} alt={s.name}/><h3>{s.name}</h3><span>Find accounts with this collection</span></button>)}</div></>}
{view==='community'&&<><div className="section-head page-heading"><div><span className="eyebrow">COMMUNITY HUB</span><h1>Talk loadouts. Meet players.</h1><p>Share listings, collections, and buying questions.</p></div><button className="primary" onClick={()=>open('post')}><Plus size={18}/>Create post</button></div><div className="tabs">{['All topics','Selling','Collections','Discussion','Community'].map(x=><button className={category===x?'selected':''} key={x} onClick={()=>setCategory(x)}>{x}</button>)}</div><div className="forum-layout"><div>{[...records.filter(x=>x.kind==='post'),...topics].filter(x=>category==='All topics'||x.category===category).map(x=><button className="topic" key={x.id} onClick={()=>open('thread',{item:x})}><span className="avatar">{x.author?.[0]}</span><div><span className="tag">{x.category}</span>{x.demo&&<span className="demo">SAMPLE</span>}<h3>{x.title}</h3><p>{x.message.slice(0,115)}</p><small>{x.author} · {x.demo?'Preview discussion':new Date(x.created).toLocaleDateString()}</small></div><span className="replies"><MessageSquare size={17}/>{records.filter(r=>r.kind==='reply'&&r.postId===x.id).length}</span></button>)}</div><aside><h3>A better place to trade.</h3><p>Post clear collection screenshots and accurate account details.</p><hr/><p>Keep passwords and recovery codes private. Discuss offers respectfully.</p><button className="quiet" onClick={()=>open('post')}>Start a discussion</button></aside></div></>}
{view==='profile'&&<><div className="profile-banner"/><section className="profile-top"><span className="avatar large">{(profileRecord?.name||profile.name)?.[0]?.toUpperCase()}</span><div><span className="eyebrow">SELLER PROFILE</span><h1>{profileRecord?.name||profile.name}</h1><p>{profileRecord?.bio||(profile.owner?.startsWith('seller')?'Sample seller profile. Listings are for preview only.':'Your listings and community activity, in one place.')}</p></div>{profile.owner===user?.id&&<button className="secondary" onClick={()=>open('profile',{item:profileRecord})}>Edit profile</button>}</section>{!user&&!selected&&<div className="empty"><User/><h3>Make it your marketplace.</h3><p>Sign in to create your seller profile, publish listings, and send inquiries.</p><a className="primary" href="/login" target="_top">Continue with Google</a></div>}{user&&<><div className="profile-trust"><TrustBadge member={profileMember}/>{profile.owner?.startsWith('seller')&&<span className="demo">SAMPLE PROFILE</span>}</div>{!profile.owner?.startsWith('seller')&&<ProfileMetrics member={profileMember} listings={all.filter(x=>x.owner===profile.owner&&!x.sold).length}/>}<ContactButtons profile={profileRecord}/>{trustError&&<div className="notice">{trustError}<button onClick={refreshTrust}>Retry</button></div>}{!selected&&<TrustPanel data={trust} records={records} onRefresh={refresh}/>}</>}<h2 className="section-title">Seller listings</h2><div className="grid">{all.filter(x=>x.owner===profile.owner).map(card)}</div>{user&&!selected&&<><div className="section-head"><h2>Your inquiries</h2><button className="quiet" onClick={()=>open('listing')}>Create a listing</button></div>{records.filter(x=>x.kind==='inquiry'&&(x.owner===user.id||x.sellerId===user.id)).map(x=><article className="inquiry" key={x.id}><strong>{x.owner===user.id?'Sent inquiry':'Buyer inquiry'} · {all.find(l=>l.id===x.listingId)?.title||'Account'}</strong><p>{x.message}</p><small>{x.author} · {new Date(x.created).toLocaleDateString()}</small></article>)}<a className="quiet signout" href="/logout" target="_top"><LogOut size={16}/>Sign out</a></>}</>}
<footer><a className="brand" href="/">VALORANT <span className="brand-sub">BUY & SELL</span></a><p>Independent community marketplace. Not affiliated with Riot Games.</p><button onClick={()=>open('about')}>About this marketplace</button></footer></main>
{modal&&<div className="modal-backdrop" onClick={()=>!saving&&setModal(null)}><section className="modal" role="dialog" aria-modal="true" aria-label={modal.kind} onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close dialog" onClick={()=>setModal(null)}><X/></button>
{modal.kind==='detail'?<><div className="detail-art"><img src={modal.item.image||skins[0].image} alt={modal.item.title}/></div><span className="eyebrow">{modal.item.demo?'SAMPLE LISTING':'ACCOUNT LISTING'} · {modal.item.region}</span><h2>{modal.item.title}</h2><div className="listing-badges">{urgencyBadge(modal.item)}{!modal.item.demo&&<TrustBadge member={sellerMember(modal.item.owner)}/>}</div><strong className="detail-price">{money(modal.item.price)}</strong><div className="facts"><span>Rank<strong>{modal.item.rank}</strong></span><span>Level<strong>{modal.item.level}</strong></span><span>Skins<strong>{modal.item.skins}</strong></span></div><div className="summary-counts">{categories.map(c=><span key={c.key}><strong>{modal.item.inventory?.[c.key]?.length||0}</strong>{c.label}</span>)}</div>{!modal.item.inventory&&<p className="form-help">Itemized inventory has not been provided for this older listing.</p>}<button className="secondary full" onClick={()=>fullAccount(modal.item)}>View full Valorant account</button><p>{modal.item.description}</p><button className="quiet" onClick={()=>{setSelected({owner:modal.item.owner,name:modal.item.author});setView('profile');setModal(null)}}><User size={17}/>View {modal.item.author}'s profile</button>{modal.item.demo?<div className="notice">Preview only. This sample account is not for sale.</div>:<>{modal.item.sold?<div className="notice">This account has a confirmed completed sale.</div>:<><ContactButtons profile={sellerProfile(modal.item.owner)} item={modal.item}/><button className="secondary full" onClick={()=>open('inquiry',{item:modal.item})}>Send website inquiry</button></>}{user?.id!==modal.item.owner&&<button className="quiet report-link" onClick={()=>open('report',{item:modal.item})}>Report this listing</button>}</>}</>:
modal.kind==='thread'?<><span className="tag">{modal.item.category}</span><h2>{modal.item.title}</h2><small>Posted by {modal.item.author}{modal.item.demo?' · Sample discussion':''}</small><p className="thread-body">{modal.item.message}</p><h3>Replies</h3>{records.filter(x=>x.kind==='reply'&&x.postId===modal.item.id).map(x=><div className="inquiry" key={x.id}><strong>{x.author}</strong><p>{x.message}</p></div>)}<button className="primary" onClick={()=>open('reply',{item:modal.item})}>Reply to discussion</button></>:
modal.kind==='about'?<><span className="eyebrow">ABOUT</span><h2>Made for the PH community.</h2><p>Compare account collections, publish seller listings, and join discussions. Sample listings demonstrate the experience; real listings appear when sellers publish them.</p><p>Buyers contact sellers directly. This website does not process payments or provide escrow.</p><p>Account transfers may be restricted by the game publisher. Check Riot’s current terms before trading.</p><a className="quiet" href="https://www.riotgames.com/en/terms-of-service" target="_blank" rel="noreferrer">Read Riot Games terms</a></>:
!user?<><User className="signin-icon"/><h2>Join the community.</h2><p>Sign in to publish listings, update your profile, or contact a seller.</p><a className="primary full" href={'/login'} target="_top">Continue with Google</a></>:modal.kind==='listing'&&(!['seller','midman'].includes(user.role)||!sellerProfile(user.id)?.facebook)?<><span className="eyebrow">SELLER SETUP</span><h2>Set up your seller profile</h2><p>Add your Facebook, email, and WhatsApp contact details, then request Seller or Midman approval from your profile’s Trust & activity section.</p><button className="primary full" onClick={()=>{setModal(null);navigate('profile')}}>Go to my profile</button></>:modal.kind==='report'?<ReportForm item={modal.item} onSaved={()=>{setModal(null);setNotice('Report submitted for administrator review.');refresh()}}/>:<><span className="eyebrow">{modal.kind==='listing'?'SELL YOUR ACCOUNT':'COMMUNITY'}</span><h2>{({listing:'Create your listing',post:'Start a conversation',profile:'Edit your profile',inquiry:'Contact the seller',reply:'Add your reply'} as any)[modal.kind]}</h2><form onSubmit={e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));if(modal.kind==='listing'){(data as any).inventory=inventory}if(modal.kind==='inquiry'){data.listingId=modal.item.id;data.sellerId=modal.item.owner}if(modal.kind==='reply')data.postId=modal.item.id;save(modal.kind,data)}}>
{modal.kind==='listing'?<><label>Listing title<input required name="title" maxLength={100} placeholder="e.g. Reaver + Prime collection"/></label><div className="form-row"><label>Price (PHP)<input required min="1" max="10000000" type="number" name="price" placeholder="3500"/></label><label>Account rank<select name="rank">{ranks.map(x=><option key={x}>{x}</option>)}</select></label></div><label>Sale urgency<select name="urgency"><option value="normal">Not rush</option><option value="rush">Rush sale</option></select></label><label>Account level<input name="level" type="number" required min="1" max="9999"/></label><label>Region<select name="region"><option>APAC</option><option>EU</option><option>NA</option></select></label><InventoryPicker value={inventory} onChange={setInventory}/><label>Featured weapon skin<select name="image" disabled={!inventory.weapons.length}>{itemsFor(inventory,'weapons').map((x:any)=><option key={x.id} value={x.image}>{x.name}</option>)}</select></label><label>Collection and account details<textarea name="description" required placeholder="List the included skins and account details. Do not include passwords."/></label><input type="hidden" name="contact" value="Contact seller through profile channels"/><p className="form-help">Your Facebook, email, and WhatsApp details from your profile appear on the listing.</p><p className="form-help">Selections describe the items you own; this website does not automatically verify account ownership.</p></>:modal.kind==='profile'?<><label>Display name<input name="name" required defaultValue={modal.item?.name||user.name}/></label><label>About you<textarea name="bio" defaultValue={modal.item?.bio}/></label><label>Facebook profile link<input type="url" name="facebook" required placeholder="https://www.facebook.com/your.profile" defaultValue={modal.item?.facebook}/></label><label>Contact email<input type="email" name="email" required placeholder="seller@example.com" defaultValue={modal.item?.email}/></label><label>WhatsApp number<input type="tel" name="whatsapp" required placeholder="+639171234567" defaultValue={modal.item?.whatsapp}/></label><p className="form-help">These contact details are visible to buyers on your profile and listings.</p></>:<>{modal.kind==='post'&&<><label>Title<input name="title" required maxLength={150}/></label><label>Category<select name="category">{['Selling','Collections','Discussion','Community'].map(x=><option key={x}>{x}</option>)}</select></label></>}<label>{modal.kind==='inquiry'?'Your message and preferred contact':'Message'}<textarea required name="message" maxLength={3000} placeholder={modal.kind==='inquiry'?'Hi! Is this account available? You can reach me at…':'Share your thoughts…'}/></label></>}
{notice&&<div className="notice" role="alert">{notice}</div>}<button className="primary full" disabled={saving} type="submit">{saving?'Saving…':modal.kind==='listing'?'Publish listing':modal.kind==='inquiry'?'Send inquiry':'Save'}</button></form></>}
</section></div>}
</div>}
