import {useState,useEffect} from 'react';
import {tradeCall,supabase} from '../lib/supabase';
import {openConversation} from './inbox';
const stages:any={awaiting_payment:'Buyer: submit payment proof',seller_review:'Seller: review payment',midman_review:'Midman: final review',revision:'Buyer: correction requested',complete:'Completed sale',legacy:'Previous confirmation flow'};
export function TransactionNotice({user}:{user:any}){const [n,setN]=useState(0);useEffect(()=>{if(!user)return;let live=true;const read=async()=>{try{const r=await tradeCall('read');if(live)setN(r.deals.filter((d:any)=>(d.buyer===user.id&&['awaiting_payment','revision'].includes(d.stage))||(d.seller===user.id&&d.stage==='seller_review')||(d.midman===user.id&&['seller_review','midman_review'].includes(d.stage))).length)}catch{}};read();const t=setInterval(read,10000);return()=>{live=false;clearInterval(t)}},[user?.id]);return user?<a href="/profile" className="channel">Transactions{n>0&&<b className="trade-count">{n}</b>}</a>:null}
function Proof({path}:{path:string}){const [url,setUrl]=useState(''),[error,setError]=useState('');useEffect(()=>{let live=true;supabase.storage.from('vm-payment-proofs').createSignedUrl(path,300).then(({data,error})=>{if(live){setUrl(data?.signedUrl||'');setError(error?.message||'')}});return()=>{live=false}},[path]);return error?<p role="alert">{error}</p>:url?<a href={url} target="_blank" rel="noreferrer"><img className="payment-proof" src={url} alt="Buyer submitted payment screenshot"/>Open screenshot</a>:<p>Loading payment proof…</p>}
export default function Transactions({member,records,onRefresh}:{member:any,records:any[],onRefresh:()=>void}){
 const [data,setData]=useState<any>({deals:[],interests:[],applications:[],outsideSales:[]}),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const name=(id:string)=>records.find(x=>x.kind==='profile'&&x.owner===id)?.name||'Member '+id.slice(0,8),title=(id:string)=>records.find(x=>x.id===id)?.title||'Account listing';
 async function refresh(){try{setData(await tradeCall('read'));setError('')}catch(e:any){setError(e.message)}}
 useEffect(()=>{refresh();const t=setInterval(()=>{if(!document.hidden)refresh()},10000);return()=>clearInterval(t)},[member.id]);
 async function act(action:string,p:any){setBusy(true);setError('');try{await tradeCall(action,p);await refresh();onRefresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function proof(e:any,d:any){e.preventDefault();const file=new FormData(e.currentTarget).get('proof') as File;if(!file?.size)return;setBusy(true);setError('');try{if(file.size>5242880||!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('Use PNG, JPG or WebP, up to 5 MB.');const path=member.id+'/'+d.id+'/'+crypto.randomUUID()+'.'+({ 'image/png':'png','image/jpeg':'jpg','image/webp':'webp'}[file.type]);const {error}=await supabase.storage.from('vm-payment-proofs').upload(path,file,{contentType:file.type,upsert:false});if(error)throw error;await tradeCall('proof',{id:d.id,path});await refresh();onRefresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const listings=records.filter(x=>x.kind==='listing'&&x.owner===member.id&&!x.sold);
 return <section className="transaction-panel"><h3>Sales & transaction desk</h3>{error&&<div className="notice" role="alert">{error}<button onClick={refresh}>Retry</button></div>}{listings.map(l=>{const interests=data.interests.filter((c:any)=>c.listing===l.id),apps=data.applications.filter((a:any)=>a.listing===l.id),assigned=data.deals.find((d:any)=>d.listing===l.id);return <article className="trust-card" key={l.id}><h3>{l.title}</h3><p>{interests.length} interested buyers · {apps.length} Midman applicants</p><div className="interested-list">{interests.map((c:any)=><div key={c.id}><strong>{name(c.buyer)}</strong><span>{c.channel}</span><button className="secondary" onClick={()=>openConversation(c.id)}>Reply to buyer</button></div>)}</div>{!assigned&&<><form onSubmit={e=>{e.preventDefault();act('start',Object.fromEntries(new FormData(e.currentTarget)))}}><input type="hidden" name="listingId" value={l.id}/><label>Choose interested buyer<select name="buyer" required><option value="">Select buyer</option>{interests.map((c:any)=><option key={c.id} value={c.buyer}>{name(c.buyer)}</option>)}</select></label><label>Assign verified Midman<select name="midman" required><option value="">Select Midman applicant</option>{apps.map((a:any)=><option key={a.member} value={a.member}>{name(a.member)}</option>)}</select></label><button className="primary" disabled={busy||!interests.length||!apps.length}>Start inside transaction</button></form><details className="outside-sale"><summary>Sold through an outside transaction?</summary><p>This marks the account Sold and records a seller-reported outside sale. It does not claim Midman verification.</p><form onSubmit={e=>{e.preventDefault();if(confirm('Mark this listing sold outside the website?'))act('outside',Object.fromEntries(new FormData(e.currentTarget)))}}><input type="hidden" name="listingId" value={l.id}/><label>Outside buyer name / reference<input name="buyerName" maxLength={150} required/></label><button className="secondary" disabled={busy}>Mark Sold · Outside transaction</button></form></details></>}{assigned&&<p>Transaction assigned: {stages[assigned.stage]}</p>}</article>})}
 {member.role==='midman'&&<div className="trust-card"><h3>Apply as verified Midman</h3><p>The seller chooses an applicant when starting the inside transaction.</p>{records.filter(l=>l.kind==='listing'&&!l.sold&&l.owner!==member.id).map(l=><div className="midman-offer" key={l.id}><strong>{l.title}</strong><button className="secondary" disabled={busy||data.applications.some((a:any)=>a.listing===l.id&&a.member===member.id)} onClick={()=>act('apply',{listingId:l.id})}>{data.applications.some((a:any)=>a.listing===l.id&&a.member===member.id)?'Applied':'Apply as Midman'}</button></div>)}</div>}
 <h3>Your assigned transactions</h3>{!data.deals.length&&<p>No assigned transactions yet.</p>}{data.deals.map((d:any)=><article className="trust-card" key={d.id}><div className="section-head"><h3>{title(d.listing)}</h3><span className="status-pill">{stages[d.stage]}</span></div><p>Buyer: {name(d.buyer)} · Seller: {name(d.seller)}{d.midman&&' · Midman: '+name(d.midman)}</p><ol className="transaction-steps"><li>Buyer pays outside and submits proof {d.buyer_confirmed?'✓':''}</li><li>Seller reviews payment {d.seller_confirmed?'✓':''}</li><li>Verified Midman reviews and ends transaction {d.midman_confirmed?'✓':''}</li></ol>{d.review_note&&<div className="notice">Correction requested: {d.review_note}</div>}{d.proof_path&&<Proof path={d.proof_path}/>}{d.buyer===member.id&&['awaiting_payment','revision'].includes(d.stage)&&<form onSubmit={e=>proof(e,d)}><p>Payment happens outside the website. Upload proof after sending payment; seller and assigned Midman can view it.</p><label>Payment screenshot (PNG/JPG/WebP, max 5 MB)<input type="file" name="proof" accept="image/png,image/jpeg,image/webp" required/></label><button className="primary" disabled={busy}>Submit proof · Notify seller & Midman</button></form>}{d.seller===member.id&&d.stage==='seller_review'&&<button className="primary" disabled={busy} onClick={()=>act('seller-approve',{id:d.id})}>Payment reviewed · Send to Midman</button>}{d.midman===member.id&&d.stage==='midman_review'&&<button className="primary" disabled={busy} onClick={()=>{if(confirm('Confirm the reviewed transaction is complete?'))act('complete',{id:d.id})}}>Final confirmation · Complete sale</button>}{((d.seller===member.id&&d.stage==='seller_review')||(d.midman===member.id&&d.stage==='midman_review'))&&<form onSubmit={e=>{e.preventDefault();act('revision',{id:d.id,...Object.fromEntries(new FormData(e.currentTarget))})}}><label>Request correction<textarea name="note" required minLength={5} maxLength={1000}/></label><button className="secondary" disabled={busy}>Return to buyer for correction</button></form>}{d.seller===member.id&&d.stage==='awaiting_payment'&&<button className="quiet" disabled={busy} onClick={()=>act('cancel',{id:d.id})}>Cancel before payment proof</button>}{d.stage==='legacy'&&<p>Previous transaction record. Use its existing confirmation flow.</p>}</article>)}{data.outsideSales.map((e:any)=><article className="trust-card" key={e.listing}><strong>{title(e.listing)} · Sold outside</strong><p>Buyer/reference: {e.buyer_name}</p><small>Seller-reported sale · {new Date(e.created).toLocaleString()}</small></article>)}</section>;
}
