import {appFetch,tradeCall} from '../lib/supabase';
import Transactions from './transactions';
'use client';
import {useState} from 'react';
import {Shield,Flag,Check,Clock} from 'lucide-react';
export function TrustBadge({member}:{member:any}){return <span className={'trust-badge '+(member?.role||'buyer')}><Shield size={13}/>{member?.admin?'Admin · ':''}{member?.role==='midman'?'Approved Midman':member?.role==='seller'?'Approved Seller':'Buyer'}{member?.suspended?' · Suspended':''}</span>}
export function ProfileMetrics({member,listings}:{member:any,listings:number}){return <div className="profile-metrics"><div><strong>{member?.credits??100}<small>/100</small></strong><span>Account credits</span></div><div><strong>{member?.confirmedReports||0}</strong><span>Confirmed reports</span></div>{(member?.admin||['seller','midman'].includes(member?.role))&&<><div><strong>{member?.sales||0}</strong><span>Recorded sales</span></div><div><strong>{member?.midmanDeals||0}</strong><span>Midman transactions</span></div><div><strong>{listings}</strong><span>Listings</span></div></>}</div>}
export async function trustAction(payload:any){const r=await appFetch('/api/trust',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d:any=await r.json();if(!r.ok)throw Error(d.error);return d}
export function ReportForm({item,onSaved}:{item:any,onSaved:()=>void}){const [error,setError]=useState(''),[busy,setBusy]=useState(false);return <><span className="eyebrow">REPORT A LISTING</span><h2>Submit for review</h2><p>Reports stay pending until an administrator reviews the evidence. Reporting alone does not reduce anyone’s credits.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');const p=Object.fromEntries(new FormData(e.currentTarget));try{await trustAction({action:'report',listingId:item.id,...p});onSaved()}catch(e:any){setError(e.message)}finally{setBusy(false)}}}><label>What happened?<textarea name="reason" required minLength={10} maxLength={2000}/></label><label>Supporting evidence<textarea name="evidence" required minLength={10} maxLength={3000} placeholder="Describe the transaction and provide links to supporting screenshots. Do not include passwords or payment credentials."/></label>{error&&<div className="notice" role="alert">{error}</div>}<button className="primary full" disabled={busy}>{busy?'Submitting…':'Submit report'}</button></form></>}
export default function TrustPanel({data,records,onRefresh}:{data:any,records:any[],onRefresh:()=>void}){
 const [notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('activity');
 async function act(p:any){setBusy(true);setNotice('');try{await trustAction(p);setNotice('Saved successfully.');onRefresh()}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}
 const member=data?.member;if(!member)return null;
 const title=(id:string)=>records.find(x=>x.id===id)?.title||id;
 const profileName=(id:string)=>records.find(x=>x.kind==='profile'&&x.owner===id)?.name||'Member '+id.slice(0,8);
 const pending=data.requests?.find((r:any)=>r.member===member.id&&r.status==='pending');
 const ownListings=records.filter(x=>x.kind==='listing'&&x.owner===member.id&&!x.sold);
 return <section className="trust-panel"><div className="section-head"><h2>Trust & activity</h2><TrustBadge member={member}/></div><div className="member-code"><span>Your member ID</span><code>{member.id}</code><small>Share this ID with the seller or midman to record a transaction.</small></div><div className="tabs"><button className={tab==='activity'?'selected':''} onClick={()=>setTab('activity')}>My activity</button><button className={tab==='role'?'selected':''} onClick={()=>setTab('role')}>Role approval</button>{member.admin&&<button className={tab==='admin'?'selected':''} onClick={()=>setTab('admin')}>Admin review</button>}</div>{notice&&<div className="notice" role="status">{notice}</div>}
 {tab==='role'&&<div className="trust-card"><h3>Choose your community role</h3><p>Buyer is the starting role. Seller and Midman require administrator approval; a badge describes your approved role, not a guarantee of any transaction.</p><div className="role-ladder"><span>1 · Buyer</span><span>2 · Approved Seller</span><span>3 · Approved Midman</span></div>{member.admin?<div><p>You are an administrator. Choose your community role directly.</p><button className="primary" disabled={busy} onClick={async()=>{setBusy(true);try{await tradeCall('admin-role',{role:'seller'});onRefresh()}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}}>Use Seller role</button> <button className="secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await tradeCall('admin-role',{role:'midman'});onRefresh()}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}}>Use Midman role</button></div>:pending?<div className="notice">Your {pending.role} request is awaiting review.</div>:member.role==='midman'?<p>You hold the highest role: Approved Midman.</p>:<form onSubmit={e=>{e.preventDefault();const p=Object.fromEntries(new FormData(e.currentTarget));act({action:'request-role',...p})}}><label>Request role<select name="role">{member.role==='buyer'&&<option value="seller">Seller</option>}<option value="midman">Midman</option></select></label><label>Experience and supporting details<textarea name="details" minLength={10} maxLength={2000} required placeholder="Describe your selling or midman experience and provide reference links."/></label><button className="primary" disabled={busy}>Submit approval request</button></form>}{data.requests?.filter((r:any)=>r.member===member.id&&r.status!=='pending').map((r:any)=><p key={r.id}>{r.role} request · {r.status}</p>)}</div>}
 {tab==='activity'&&<><div className="trust-card policy"><Shield size={21}/><div><h3>Credits policy</h3><p>Start with 100 credits. Each admin-confirmed scam report deducts 25. At zero credits, website access is suspended for 7 days. After expiry, access returns with 25 credits. Pending or dismissed reports do not deduct credits.</p></div></div><Transactions member={member} records={records} onRefresh={onRefresh}/>{data.deals?.filter((d:any)=>d.stage==='legacy'&&(d.buyer===member.id||d.midman===member.id)).map((d:any)=><article className="trust-card" key={d.id}><p>{title(d.listing)} · Previous transaction</p><button className="secondary" disabled={busy} onClick={()=>act({action:'confirm-deal',id:d.id})}>Confirm previous transaction</button></article>)}<h3>Your submitted reports</h3>{!data.reports?.filter((r:any)=>r.reporter===member.id).length&&<p className="form-help">No reports submitted.</p>}{data.reports?.filter((r:any)=>r.reporter===member.id).map((r:any)=><article className="trust-card" key={r.id}><strong>{title(r.listing)}</strong><p>{r.reason}</p><span className="status-pill">{r.status}</span></article>)}</>}
 {tab==='admin'&&member.admin&&<><div className="notice">Review evidence before confirming a scam report. Confirming deducts 25 credits and can trigger a 7-day suspension.</div><h3>Pending role requests</h3>{!data.requests?.some((r:any)=>r.status==='pending')&&<p className="form-help">No pending role requests.</p>}{data.requests?.filter((r:any)=>r.status==='pending').map((r:any)=><article className="trust-card" key={r.id}><strong>{profileName(r.member)} · Requested {r.role}</strong><p>{r.details}</p><div className="admin-actions"><button className="primary" disabled={busy} onClick={()=>act({action:'review-role',id:r.id,decision:'approved'})}>Approve {r.role}</button><button className="secondary" disabled={busy} onClick={()=>act({action:'review-role',id:r.id,decision:'rejected'})}>Reject request</button></div></article>)}<h3>Pending scam reports</h3>{!data.reports?.some((r:any)=>r.status==='pending')&&<p className="form-help">No pending reports.</p>}{data.reports?.filter((r:any)=>r.status==='pending').map((r:any)=><article className="trust-card" key={r.id}><strong>{title(r.listing)} · {profileName(r.target)}</strong><p><b>Report:</b> {r.reason}</p><p><b>Evidence:</b> {r.evidence}</p><small>Reported by {profileName(r.reporter)} · {new Date(r.created).toLocaleDateString()}</small><div className="admin-actions"><button className="primary" disabled={busy} onClick={()=>act({action:'review-report',id:r.id,decision:'confirmed'})}>Confirm scam · −25 credits</button><button className="secondary" disabled={busy} onClick={()=>act({action:'review-report',id:r.id,decision:'dismissed'})}>Dismiss report</button></div></article>)}<h3>Review history</h3>{data.reports?.filter((r:any)=>r.status!=='pending').map((r:any)=><div className="trust-card" key={r.id}>{title(r.listing)} · {r.status}</div>)}</>}
 </section>
}
